Repository oogeso/oogeso, pull requests merged in 2021-12, with the labels that each got.

#60 Ci: Add GitHub pull request template
  .github/pull_request_template.md
  .github/release_template.md
  .github/workflows/release.yml
Labels: ci, chore

#64 ci: Build and support Python 3.10
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: ci

#53 chore: Pre-commit formatting and code issues fix
  .isort.cfg
  .pre-commit-config.yaml
  README.md
  bin/optimize_power_system.py
  bin/read_oogeso_data.py
  src/oogeso/__init__.py
  src/oogeso/core/devices/__init__.py
  src/oogeso/core/devices/base.py
  src/oogeso/core/devices/compressor.py
  src/oogeso/core/devices/electrolyser.py
  src/oogeso/core/devices/fuelcell.py
  src/oogeso/core/devices/gasheater.py
  src/oogeso/core/devices/gasturbine.py
  src/oogeso/core/devices/heatpump.py
  src/oogeso/core/devices/pump.py
  src/oogeso/core/devices/separator.py
  src/oogeso/core/devices/sink.py
  src/oogeso/core/devices/source.py
  src/oogeso/core/devices/storage.py
  src/oogeso/core/devices/well.py
  src/oogeso/core/milp_plot.py
  src/oogeso/core/networks/__init__.py
  src/oogeso/core/networks/edge.py
  src/oogeso/core/networks/electricalsystem.py
  src/oogeso/core/networks/electricity.py
  src/oogeso/core/networks/network.py
  src/oogeso/core/networks/network_node.py
  src/oogeso/core/networks/pipelines.py
  src/oogeso/core/optimiser.py
  src/oogeso/core/simulator.py
  src/oogeso/dto/__init__.py
  src/oogeso/dto/oogeso_input_data_objects.py
  src/oogeso/dto/oogeso_input_data_objects_multienergy.py
  src/oogeso/dto/oogeso_output_data_objects.py
  src/oogeso/dto/serialisation.py
  src/oogeso/io/__init__.py
  src/oogeso/io/file_io.py
  src/oogeso/plots/__init__.py
  src/oogeso/plots/plots.py
  src/oogeso/result_analysis.py
  src/oogeso/utils/__init__.py
  src/oogeso/utils/util.py
  tests/conftest.py
  tests/test_cbc.py
  tests/test_devices_create.py
  tests/test_io.py
  tests/test_optimisation_model.py
  tests/test_pipelines.py
  tests/test_simulator.py
  tests/test_testcase.py
Labels: chore

#70 adding options to provide solver excecutable and solver options
  src/oogeso/core/optimiser.py
  src/oogeso/core/simulator.py
  tests/test_simulator.py
Labels: ci
