Repository oogeso/oogeso, pull requests merged in 2021-11, with the labels that each got.

#36 CI: Build, release and publish with Poetry and GitHub Actions
  .github/RELEASE-TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/oogeso.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  setup.py
  src/oogeso/core/__init__.py
  tests/test_io.py
  tests/test_testcase.py
Labels: ci

#40 feat: Convert from HDF5 to Parquet. Backward compatible
  .github/workflows/build.yml
  .gitignore
  poetry.lock
  pyproject.toml
  src/oogeso/io/file_io.py
  tests/test_io.py
Labels: enhancement, ci

#44 Made ResultObject fields optional with default None.
  src/oogeso/core/simulator.py
  src/oogeso/dto/oogeso_output_data_objects.py
  src/oogeso/dto/serialisation.py
  src/oogeso/plots/plots.py
  tests/test_testcase.py
Labels: bug

#50 ci: Bump release and publish to Python 3.9 build
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: ci

#47 Create CI pipeline that builds and runs CBC-optimizer tests
  .github/workflows/cbc-optimizer-ci.yml
  CHANGES.txt
  Dockerfile
  poetry.lock
  tests/test_cbc.py
  tests/test_testcase.py
Labels: ci, test

#51 Ci/35 add pre commit code check
  .bandit
  .black.ini
  .flake8
  .pre-commit-config.yaml
  README.md
  pyproject.toml
Labels: ci

#49 docs: Update README.md after publishing to PyPi
  README.md
  userguide.md
Labels: documentation
