Repository oogeso/oogeso, pull requests merged in 2022-01, with the labels that each got.

#73 fix: Bug fix in kpi calculation
  src/oogeso/result_analysis.py
Labels: bug

#75 ci: Update to version v0.4.0 for release
  pyproject.toml
Labels: ci

#77 Fix/71 code quality issues
  .gitignore
  src/oogeso/core/devices/storage.py
  src/oogeso/core/networks/pipelines.py
  src/oogeso/core/optimiser.py
  src/oogeso/dto/serialisation.py
  src/oogeso/plots/plots.py
Labels: bug, chore

#74 test: Unit tests for pyomo model device constraints
  src/oogeso/core/devices/compressor.py
  src/oogeso/core/devices/gasheater.py
  src/oogeso/core/devices/heatpump.py
  src/oogeso/core/devices/separator.py
  src/oogeso/core/devices/storage.py
  src/oogeso/core/optimiser.py
  src/oogeso/dto/__init__.py
  src/oogeso/dto/oogeso_input_data_objects_multienergy.py
  src/oogeso/utils/util.py
  tests/test_devices_constraints.py
  tests/test_devices_create.py
Labels: test
